# See https://golangci-lint.run/usage/configuration/ for configuration options
run:
  timeout: 5m
  skip-dirs:
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.lr\\.go$"
  modules-download-mode: readonly