# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# See https://golangci-lint.run/usage/configuration/ for configuration options
run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.lr\\.go$"