# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# See https://golangci-lint.run/usage/configuration/ for configuration options
version: "2"
run:
  modules-download-mode: readonly
linters:
  exclusions:
    paths:
      - .*\.pb\.go$
      - .*\.lr\.go$
