# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
version: 2
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - make generate
    # Check plugin compatibility with required version of the Packer SDK
    - make plugin-check
builds:
  # building the new packer-plugin-cnspec
  - id: packer-plugin-cnspec-linux
    binary: 'packer-plugin-cnspec_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - linux
    goarch:
      - amd64
      - '386'
      - arm64
      - arm
    ldflags:
      - -s -w -X go.mondoo.com/cnquery/v10.Version={{ .Env.CNSPEC_VERSION }} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Version={{.Version}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Build={{.ShortCommit}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Date={{.Date}}
  - id: packer-plugin-cnspec-windows
    binary: 'packer-plugin-cnspec_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X go.mondoo.com/cnquery/v10.Version={{ .Env.CNSPEC_VERSION }} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Version={{.Version}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Build={{.ShortCommit}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Date={{.Date}}
  - id: packer-plugin-cnspec-darwin
    binary: 'packer-plugin-cnspec_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X go.mondoo.com/cnquery/v10.Version={{ .Env.CNSPEC_VERSION }} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Version={{.Version}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Build={{.ShortCommit}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Date={{.Date}}
  
  # building fall-back binaries
  - id: packer-plugin-mondoo
    binary: 'packer-plugin-mondoo_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Version={{.Version}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Build={{.ShortCommit}} -X go.mondoo.com/packer-plugin-cnspec/provisioner/version.Date={{.Date}}

archives:
  - id: releases-packer-plugin-cnspec
    builds:
      - packer-plugin-cnspec-linux
      - packer-plugin-cnspec-windows
      - packer-plugin-cnspec-darwin
    name_template: 'packer-plugin-cnspec_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    files:
      - none*
  - id: releases-packer-plugin-mondoo
    builds:
      - packer-plugin-mondoo
    name_template: 'packer-plugin-mondoo_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    files:
      - none*
checksum:
  name_template: 'packer-plugin-cnspec_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  use: github-native
